# Generated by Django 6.0.5 on 2026-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityrecord',
            old_name='emission_kgco2e',
            new_name='emissions_kgco2e',
        ),
        migrations.RenameField(
            model_name='ingestionrun',
            old_name='tota_rows',
            new_name='total_rows',
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='quantity_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='unit_original',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='scope',
            field=models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('suspicious', 'Suspicious'), ('failed', 'Failed'), ('approved', 'Approved'), ('locked', 'Locked')], default='pending', max_length=50),
        ),
    ]
